# Generated by Django 4.1.5 on 2023-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNAB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="cnab/")),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CNABData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("data", models.CharField(max_length=10)),
                ("value", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=20)),
                ("hour", models.CharField(max_length=10)),
                ("store_owner", models.CharField(max_length=50)),
                ("store_name", models.CharField(max_length=50)),
            ],
        ),
    ]
